name: "My spotify playists"
author: "Nacho270"
description: "Finds a tag in my README and inserts a list of my spotify playlists"

inputs:
  readme_path:
    description: "Path of the readme file you want to update"
    default: "./README.md"
    required: false
  gh_token:
    description: "GitHub access token with Repo scope"
    required: false
    default: ${{ github.token }}
  commit_message:
    description: "Commit message used while committing to the repo"
    default: "Updated with the spotify playlists"
    required: false
  committer_username:
    description: "Username used while committing to the repo"
    default: "spotity-playlists-bot"
    required: false
  committer_email:
    description: "Email id used while committing to the repo"
    default: "spotify-playlists-bot@nacho.com"
    required: false

runs:
  using: node16
  main: dist/my-playlists.js
branding:
  icon: "activity"
  color: "blue"
